[build]
  command = "npm run generate"
  publish = "dist"

[functions]
  directory = "netlify/functions"


[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://challenges.cloudflare.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data:;
      connect-src 'self';
    """
  